repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: \.vscode.*/
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        description: Hook for a version of eslint that the mirror repo skipped.
        language: script
        entry: node_modules/.bin/eslint --fix
        args: []
        types: [file]
        files: \.[jt]s$

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: Hook for a version of prettier that the mirror repo skipped.
        language: script
        entry: node_modules/.bin/prettier --write --ignore-unknown
        args: []
        types: [text]
        require_serial: false
